sudo: false
language: java
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dgpg.skip=true
script: mvn test -Dgpg.skip=true
cache:
  directories:
    - '$HOME/.m2/repository'

